[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
factor = "0.4.0"
fancy-regex = "0.12.0"
fn-cache = "1.1.1"
itertools = "0.12.0"
md5 = "0.7.0"
regex = "1.10.2"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.108"
